
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  service:
    build:
      context: .
      dockerfile: ./Dockerfile.service
    ports:
      - "9000:9000"
    volumes:
      - ./service:/var/www/service
    depends_on:
      - mongodb

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - service
    

volumes:
  mongodb_data: